-- ============================================================
-- Migration 003: fulfilment schema extensions
--
-- Extends the orders table with fulfilment lifecycle columns and
-- introduces a normalised order_items table.  All other pipeline
-- subtasks (Trigger.dev job, status-tracking webhook) depend on
-- this schema — no further DDL changes should be required.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Fulfillment status enum
-- ------------------------------------------------------------
do $$ begin
  create type fulfilment_status as enum (
    'paid',
    'submitted',
    'in_production',
    'shipped',
    'delivered',
    'failed'
  );
exception
  when duplicate_object then null;
end $$;

-- ------------------------------------------------------------
-- 2. Alter orders table
--
-- The existing `status` column uses a text CHECK constraint
-- (values: pending, paid, fulfilled, failed).  We replace it
-- with the new enum.  Existing rows that have status='paid'
-- map directly; 'fulfilled' → 'delivered' is the closest
-- semantic match for any data already present.
-- ------------------------------------------------------------

-- Drop the old check constraint (name generated by Postgres).
alter table orders
  drop constraint if exists orders_status_check;

-- Drop the text default before casting to the enum.
alter table orders
  alter column status drop default;

-- Cast existing text values → new enum (best-effort mapping).
alter table orders
  alter column status type fulfilment_status
  using (
    case status
      when 'paid'      then 'paid'::fulfilment_status
      when 'fulfilled' then 'delivered'::fulfilment_status
      when 'failed'    then 'failed'::fulfilment_status
      else                  'paid'::fulfilment_status
    end
  );

-- Reset the column default to the typed enum literal.
alter table orders
  alter column status set default 'paid'::fulfilment_status;

-- Fulfilment supplier columns (all nullable until job runs).
alter table orders
  add column if not exists supplier_order_id text,
  add column if not exists tracking_number   text,
  add column if not exists carrier           text;

-- Indexes for the fulfilment pipeline query patterns.
create index if not exists orders_supplier_order_id_idx
  on orders (supplier_order_id)
  where supplier_order_id is not null;

create index if not exists orders_fulfilment_status_idx
  on orders (status);

-- ------------------------------------------------------------
-- 3. order_items table
--
-- Normalised line items extracted from the Stripe session.
-- The denormalised `line_items` JSONB column on `orders` is
-- retained for backward compatibility with the webhook handler.
-- ------------------------------------------------------------
create table if not exists order_items (
  id                  uuid        primary key default gen_random_uuid(),
  order_id            uuid        not null references orders (id) on delete cascade,
  product_sku         text        not null,   -- internal SKU, e.g. "ns-01-30x40-print"
  supplier_product_id text,                   -- POD supplier's product/SKU code
  quantity            integer     not null default 1 check (quantity > 0),
  unit_price_cents    integer     not null check (unit_price_cents >= 0),
  currency            text        not null default 'eur',
  description         text,
  created_at          timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on order_items (order_id);

-- ------------------------------------------------------------
-- 4. Row Level Security
-- ------------------------------------------------------------

-- order_items inherits the same access model as orders.
alter table order_items enable row level security;

-- Service role: Supabase service role bypasses RLS automatically.
-- No explicit policy is needed for the service role.

-- Authenticated users may read their own orders (matched by
-- customer_email = auth.email()).  Write operations remain
-- service-role only — no authenticated INSERT/UPDATE/DELETE.
create policy "authenticated users can read own orders"
  on orders
  for select
  to authenticated
  using (customer_email = auth.email());

create policy "authenticated users can read own order items"
  on order_items
  for select
  to authenticated
  using (
    order_id in (
      select id from orders where customer_email = auth.email()
    )
  );

-- Anon role: no access to orders or order_items.
-- (No policy = no access when RLS is enabled.)

-- ------------------------------------------------------------
-- 5. updated_at trigger (orders already has the column)
-- ------------------------------------------------------------
create or replace function touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create or replace trigger orders_updated_at
  before update on orders
  for each row execute function touch_updated_at();
